### ISSUE TITLE
unsupported protocol scheme ""

### ISSUE THREAD

**Issue by kelvich** [vito/houdini#8]
Hi, when registering houdini-worker I got following error on ATC:

```json
{"timestamp":"1492592313.233969212",
"source":"atc",
"message":"atc.create-build.do.aggregate.get.volume-on.failed-to-list-volumes",
"log_level":2,
"data":{"error":"Get /volumes?initialized=yep\u0026resource-params=04f8ff2682604862e405bf88de102ed7710ac45c1205957625e4ee3e5f5a2241e453614acc451345b91bafc88f38804019c7492444595674e94e8cf4be53817f\u0026resource-source=088d6b72d3ace5afc37eda80b3dc1c9c90e0eff28e06c90605b1fc7f99d519d5d6e6afe1d2a2960a19a37d7970d1f40b682b606c98b9487ef620e521fc626f07\u0026resource-type=archive\u0026resource-version=null: unsupported protocol scheme \"\"",
"name":"postgresql",
"session":"112.3.2.1.10"}}
```

interesting part here is probably " unsupported protocol scheme \"\""

After some googleing i've run into suggestions to set CONCOURSE_EXTERNAL_URL, however setting this one everywhere (worker, atc, client) doesn't help.

Starting ```concourse worker``` instead of houdini on mac seems to work well, but i need to test on lot of systems (sparc, freebsd, old linuxes) so trying to use houdini instead.

**Comment by kelvich** [comment]
Ok, I was able to build concourse/bin for freebsd, so it solves issue for me.

**Comment by jtarchie** [comment]
@kelvich, does this mean you can close this issue?

**Comment by kelvich** [comment]
@jtarchie sure
